version: '3.8'

services:
  app:
    container_name: dev-container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      # dockerfile: /home/mlawson/Workspace/gpt_workspace/gpt4all-ui/.devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
  db:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres-data: